packages:
  - .
  - packages/*
overrides:
  lodash: 4.18.1
  playwright: 1.55.1
  '@playwright/test': 1.55.1
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
